// AUTO-GENERATED by scripts/generate-default-resume.mjs — do not edit.
// Mirrors resumes/manifest.json "defaultFile" so the bundled / SSG default
// (rendered even with JavaScript disabled) always matches the manifest.
import data from '../../resumes/product-engineer-2026-June-07.json';

export const DEFAULT_RESUME_PATH = 'product-engineer-2026-June-07.json';
export default data;
